[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
filterwarnings = [
    "ignore:builtin type SwigPyPacked.*:DeprecationWarning",
    "ignore:builtin type SwigPyObject.*:DeprecationWarning",
    "ignore:builtin type swigvarlink.*:DeprecationWarning",
]
